backend:
  name: git-gateway
  branch: main

  # Required for OAuth to work:
  proxy_url: https://your-site.netlify.app/api/v1

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  # BLOG POSTS
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Featured Image", widget: "image" }
      - { name: "excerpt", label: "Excerpt", widget: "text" }
      - { name: "body", label: "Content", widget: "markdown" }

  # PROGRAMMES
  - name: "programmes"
    label: "Programmes"
    folder: "programmes"
    create: true
    identifier_field: "slug"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "slug", label: "URL Slug", widget: "string" }
      - { name: "price", label: "Price", widget: "number" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "description", label: "Description", widget: "markdown" }